-- ============================================================
-- INSERT: AekAds Gandhinagar (20 Residential + 6 Corporate = 26 entries)
-- Network: AekAds | City: Gandhinagar | State: Gujarat
-- Residential Rate: ₹1,500/screen/month → ₹55/screen/day
-- Corporate Rate: ₹3,000/screen/month → ₹110/screen/day
-- Outdoor Rate: ₹1,00,000/screen/month → ₹3,667/screen/day
-- Duration: 10 sec per slot | Loop: 90 sec (1.5 min)
-- min_booking_days = 30 (monthly commitment)
-- ============================================================

BEGIN;

-- ============================================================
-- GANDHINAGAR RESIDENTIAL (20 properties, 85 screens)
-- ============================================================

INSERT INTO screens (
  name, category, display_format, resolution, duration_per_slot,
  venue_name, location, city, state, pincode, latitude, longitude,
  venue_category, avg_daily_footfall, traffic_type, time_of_day_activity,
  environment_type, visibility, description,
  custom_operating_hours_start, custom_operating_hours_end,
  custom_operating_days,
  detailed_age_groups, gender_orientation, income_level,
  occupation_mix, lifestyle_tags, avg_dwell_time,
  user_intent, user_mood,
  is_multi_screen, number_of_screens, price_per_day, min_booking_days,
  loop_duration, max_brands_per_loop, playback_slots_per_hour,
  content_types_supported,
  type, size, operational_hours,
  status, owned_by_admin
) VALUES
-- 1. Samanvay, Kudasan — 6 screens, 240 households, 960 reach → ₹330/day
(
  'AekAds Samanvay Gandhinagar - Digital Display',
  'Digital Display', 'Portrait', '1080x1920', 10,
  'Samanvay',
  'Samanvay, Kudasan, Gandhinagar, Gujarat 382421',
  'Gandhinagar', 'Gujarat', '382421', 23.17641563, 72.63138427,
  'Residential Society', 960, 'Pedestrian',
  ARRAY['Morning Rush','Evening Leisure'],
  'Indoor', 'Medium',
  '43-inch Dual LED screens at Samanvay, Kudasan. 6 towers, 6 screens serving 240 households.',
  '06:00', '00:00',
  ARRAY['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
  ARRAY['Young Adults (18-25)','Adults (26-40)','Middle Age (41-55)'],
  'Mixed Gender', 'Middle Income',
  ARRAY['Working Professionals','Homemakers','Families'],
  ARRAY['Daily Commuters','Urban Residents'],
  5,
  ARRAY['Daily Living','Commuting'], ARRAY['Relaxed','Routine'],
  true, 6, 330, 30,
  90, 9, 40,
  ARRAY['Video','Static Image'],
  'Digital Display', '43 Inches (1080 x 1920)', '06:00 AM - 12:00 AM',
  'active', true
),
-- 2. Samved Dreams, Kudasan — 10 screens, 285 households, 1040 reach → ₹550/day
(
  'AekAds Samved Dreams Gandhinagar - Digital Display',
  'Digital Display', 'Portrait', '1080x1920', 10,
  'Samved Dreams',
  'Samved Dreams, Kudasan, Gandhinagar, Gujarat 382421',
  'Gandhinagar', 'Gujarat', '382421', 23.18520513, 72.61195121,
  'Residential Society', 1040, 'Pedestrian',
  ARRAY['Morning Rush','Evening Leisure'],
  'Indoor', 'Medium',
  '43-inch Dual LED screens at Samved Dreams, Kudasan. 6 towers, 10 screens serving 285 households.',
  '06:00', '00:00',
  ARRAY['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
  ARRAY['Young Adults (18-25)','Adults (26-40)','Middle Age (41-55)'],
  'Mixed Gender', 'Middle Income',
  ARRAY['Working Professionals','Homemakers','Families'],
  ARRAY['Daily Commuters','Urban Residents'],
  5,
  ARRAY['Daily Living','Commuting'], ARRAY['Relaxed','Routine'],
  true, 10, 550, 30,
  90, 9, 40,
  ARRAY['Video','Static Image'],
  'Digital Display', '43 Inches (1080 x 1920)', '06:00 AM - 12:00 AM',
  'active', true
),
-- 3. Sarthak Shrinand, Kudasan — 3 screens, 130 households, 520 reach → ₹165/day
(
  'AekAds Sarthak Shrinand Gandhinagar - Digital Display',
  'Digital Display', 'Portrait', '1080x1920', 10,
  'Sarthak Shrinand',
  'Sarthak Shrinand, Kudasan, Gandhinagar, Gujarat 382421',
  'Gandhinagar', 'Gujarat', '382421', 23.16403027, 72.63878568,
  'Residential Society', 520, 'Pedestrian',
  ARRAY['Morning Rush','Evening Leisure'],
  'Indoor', 'Medium',
  '43-inch Dual LED screens at Sarthak Shrinand, Kudasan. 3 towers, 3 screens serving 130 households.',
  '06:00', '00:00',
  ARRAY['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
  ARRAY['Young Adults (18-25)','Adults (26-40)','Middle Age (41-55)'],
  'Mixed Gender', 'Middle Income',
  ARRAY['Working Professionals','Homemakers','Families'],
  ARRAY['Daily Commuters','Urban Residents'],
  5,
  ARRAY['Daily Living','Commuting'], ARRAY['Relaxed','Routine'],
  true, 3, 165, 30,
  90, 9, 40,
  ARRAY['Video','Static Image'],
  'Digital Display', '43 Inches (1080 x 1920)', '06:00 AM - 12:00 AM',
  'active', true
),
-- 4. Sarthak Serenity, Kudasan — 2 screens, 53 households, 220 reach → ₹110/day
(
  'AekAds Sarthak Serenity Gandhinagar - Digital Display',
  'Digital Display', 'Portrait', '1080x1920', 10,
  'Sarthak Serenity',
  'Sarthak Serenity, Kudasan, Gandhinagar, Gujarat 382823',
  'Gandhinagar', 'Gujarat', '382823', 23.17450127, 72.63996943,
  'Residential Society', 220, 'Pedestrian',
  ARRAY['Morning Rush','Evening Leisure'],
  'Indoor', 'Medium',
  '43-inch Dual LED screens at Sarthak Serenity, Kudasan. 2 towers, 2 screens serving 53 households.',
  '06:00', '00:00',
  ARRAY['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
  ARRAY['Young Adults (18-25)','Adults (26-40)','Middle Age (41-55)'],
  'Mixed Gender', 'Middle Income',
  ARRAY['Working Professionals','Homemakers','Families'],
  ARRAY['Daily Commuters','Urban Residents'],
  5,
  ARRAY['Daily Living','Commuting'], ARRAY['Relaxed','Routine'],
  true, 2, 110, 30,
  90, 9, 40,
  ARRAY['Video','Static Image'],
  'Digital Display', '43 Inches (1080 x 1920)', '06:00 AM - 12:00 AM',
  'active', true
),
-- 5. Radian Residency, Kudasan — 4 screens, 91 households, 360 reach → ₹220/day
(
  'AekAds Radian Residency Gandhinagar - Digital Display',
  'Digital Display', 'Portrait', '1080x1920', 10,
  'Radian Residency',
  'Radian Residency, Kudasan, Gandhinagar, Gujarat 382421',
  'Gandhinagar', 'Gujarat', '382421', 23.18306593, 72.62342141,
  'Residential Society', 360, 'Pedestrian',
  ARRAY['Morning Rush','Evening Leisure'],
  'Indoor', 'Medium',
  '43-inch Dual LED screens at Radian Residency, Kudasan. 4 towers, 4 screens serving 91 households.',
  '06:00', '00:00',
  ARRAY['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
  ARRAY['Young Adults (18-25)','Adults (26-40)','Middle Age (41-55)'],
  'Mixed Gender', 'Middle Income',
  ARRAY['Working Professionals','Homemakers','Families'],
  ARRAY['Daily Commuters','Urban Residents'],
  5,
  ARRAY['Daily Living','Commuting'], ARRAY['Relaxed','Routine'],
  true, 4, 220, 30,
  90, 9, 40,
  ARRAY['Video','Static Image'],
  'Digital Display', '43 Inches (1080 x 1920)', '06:00 AM - 12:00 AM',
  'active', true
),
-- 6. Samarth-56, Sargasan — 2 screens, 56 households, 224 reach → ₹110/day
(
  'AekAds Samarth-56 Gandhinagar - Digital Display',
  'Digital Display', 'Portrait', '1080x1920', 10,
  'Samarth-56',
  'Samarth-56, Sargasan, Gandhinagar, Gujarat 382421',
  'Gandhinagar', 'Gujarat', '382421', 23.187291, 72.62064082,
  'Residential Society', 224, 'Pedestrian',
  ARRAY['Morning Rush','Evening Leisure'],
  'Indoor', 'Medium',
  '43-inch Dual LED screens at Samarth-56, Sargasan. 2 towers, 2 screens serving 56 households.',
  '06:00', '00:00',
  ARRAY['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
  ARRAY['Young Adults (18-25)','Adults (26-40)','Middle Age (41-55)'],
  'Mixed Gender', 'Middle Income',
  ARRAY['Working Professionals','Homemakers','Families'],
  ARRAY['Daily Commuters','Urban Residents'],
  5,
  ARRAY['Daily Living','Commuting'], ARRAY['Relaxed','Routine'],
  true, 2, 110, 30,
  90, 9, 40,
  ARRAY['Video','Static Image'],
  'Digital Display', '43 Inches (1080 x 1920)', '06:00 AM - 12:00 AM',
  'active', true
),
-- 7. Manorath Malhar, Sargasan — 2 screens, 60 households, 240 reach → ₹110/day
(
  'AekAds Manorath Malhar Gandhinagar - Digital Display',
  'Digital Display', 'Portrait', '1080x1920', 10,
  'Manorath Malhar',
  'Manorath Malhar, Sargasan, Gandhinagar, Gujarat 382421',
  'Gandhinagar', 'Gujarat', '382421', 23.19558712, 72.60815904,
  'Residential Society', 240, 'Pedestrian',
  ARRAY['Morning Rush','Evening Leisure'],
  'Indoor', 'Medium',
  '43-inch Dual LED screens at Manorath Malhar, Sargasan. 2 towers, 2 screens serving 60 households.',
  '06:00', '00:00',
  ARRAY['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
  ARRAY['Young Adults (18-25)','Adults (26-40)','Middle Age (41-55)'],
  'Mixed Gender', 'Middle Income',
  ARRAY['Working Professionals','Homemakers','Families'],
  ARRAY['Daily Commuters','Urban Residents'],
  5,
  ARRAY['Daily Living','Commuting'], ARRAY['Relaxed','Routine'],
  true, 2, 110, 30,
  90, 9, 40,
  ARRAY['Video','Static Image'],
  'Digital Display', '43 Inches (1080 x 1920)', '06:00 AM - 12:00 AM',
  'active', true
),
-- 8. Shreeji Swastik, Sargasan — 3 screens, 124 households, 496 reach → ₹165/day
(
  'AekAds Shreeji Swastik Gandhinagar - Digital Display',
  'Digital Display', 'Portrait', '1080x1920', 10,
  'Shreeji Swastik',
  'Shreeji Swastik, Sargasan, Gandhinagar, Gujarat 382421',
  'Gandhinagar', 'Gujarat', '382421', 23.19422731, 72.6046508,
  'Residential Society', 496, 'Pedestrian',
  ARRAY['Morning Rush','Evening Leisure'],
  'Indoor', 'Medium',
  '43-inch Dual LED screens at Shreeji Swastik, Sargasan. 3 towers, 3 screens serving 124 households.',
  '06:00', '00:00',
  ARRAY['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
  ARRAY['Young Adults (18-25)','Adults (26-40)','Middle Age (41-55)'],
  'Mixed Gender', 'Middle Income',
  ARRAY['Working Professionals','Homemakers','Families'],
  ARRAY['Daily Commuters','Urban Residents'],
  5,
  ARRAY['Daily Living','Commuting'], ARRAY['Relaxed','Routine'],
  true, 3, 165, 30,
  90, 9, 40,
  ARRAY['Video','Static Image'],
  'Digital Display', '43 Inches (1080 x 1920)', '06:00 AM - 12:00 AM',
  'active', true
),
-- 9. Sagar Residency, Sargasan — 4 screens, 112 households, 448 reach → ₹220/day
(
  'AekAds Sagar Residency Gandhinagar - Digital Display',
  'Digital Display', 'Portrait', '1080x1920', 10,
  'Sagar Residency',
  'Sagar Residency, Sargasan, Gandhinagar, Gujarat 382421',
  'Gandhinagar', 'Gujarat', '382421', 23.16267584, 72.64473894,
  'Residential Society', 448, 'Pedestrian',
  ARRAY['Morning Rush','Evening Leisure'],
  'Indoor', 'Medium',
  '43-inch Dual LED screens at Sagar Residency, Sargasan. 4 towers, 4 screens serving 112 households.',
  '06:00', '00:00',
  ARRAY['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
  ARRAY['Young Adults (18-25)','Adults (26-40)','Middle Age (41-55)'],
  'Mixed Gender', 'Middle Income',
  ARRAY['Working Professionals','Homemakers','Families'],
  ARRAY['Daily Commuters','Urban Residents'],
  5,
  ARRAY['Daily Living','Commuting'], ARRAY['Relaxed','Routine'],
  true, 4, 220, 30,
  90, 9, 40,
  ARRAY['Video','Static Image'],
  'Digital Display', '43 Inches (1080 x 1920)', '06:00 AM - 12:00 AM',
  'active', true
),
-- 10. Shree Ganesh Era, Sargasan — 2 screens, 60 households, 250 reach → ₹110/day
(
  'AekAds Shree Ganesh Era Gandhinagar - Digital Display',
  'Digital Display', 'Portrait', '1080x1920', 10,
  'Shree Ganesh Era',
  'Shree Ganesh Era, Sargasan, Gandhinagar, Gujarat 382421',
  'Gandhinagar', 'Gujarat', '382421', 23.19168484, 72.6048053,
  'Residential Society', 250, 'Pedestrian',
  ARRAY['Morning Rush','Evening Leisure'],
  'Indoor', 'Medium',
  '43-inch Dual LED screens at Shree Ganesh Era, Sargasan. 2 towers, 2 screens serving 60 households.',
  '06:00', '00:00',
  ARRAY['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
  ARRAY['Young Adults (18-25)','Adults (26-40)','Middle Age (41-55)'],
  'Mixed Gender', 'Middle Income',
  ARRAY['Working Professionals','Homemakers','Families'],
  ARRAY['Daily Commuters','Urban Residents'],
  5,
  ARRAY['Daily Living','Commuting'], ARRAY['Relaxed','Routine'],
  true, 2, 110, 30,
  90, 9, 40,
  ARRAY['Video','Static Image'],
  'Digital Display', '43 Inches (1080 x 1920)', '06:00 AM - 12:00 AM',
  'active', true
),
-- 11. Hari Aalay, Sargasan — 3 screens, 98 households, 396 reach → ₹165/day
(
  'AekAds Hari Aalay Gandhinagar - Digital Display',
  'Digital Display', 'Portrait', '1080x1920', 10,
  'Hari Aalay',
  'Hari Aalay, Sargasan, Gandhinagar, Gujarat 382421',
  'Gandhinagar', 'Gujarat', '382421', 23.18520262, 72.61898757,
  'Residential Society', 396, 'Pedestrian',
  ARRAY['Morning Rush','Evening Leisure'],
  'Indoor', 'Medium',
  '43-inch Dual LED screens at Hari Aalay, Sargasan. 3 towers, 3 screens serving 98 households.',
  '06:00', '00:00',
  ARRAY['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
  ARRAY['Young Adults (18-25)','Adults (26-40)','Middle Age (41-55)'],
  'Mixed Gender', 'Middle Income',
  ARRAY['Working Professionals','Homemakers','Families'],
  ARRAY['Daily Commuters','Urban Residents'],
  5,
  ARRAY['Daily Living','Commuting'], ARRAY['Relaxed','Routine'],
  true, 3, 165, 30,
  90, 9, 40,
  ARRAY['Video','Static Image'],
  'Digital Display', '43 Inches (1080 x 1920)', '06:00 AM - 12:00 AM',
  'active', true
),
-- 12. Satvan Bellevue, Rayasan Rd — 5 screens, 180 households, 730 reach → ₹275/day
(
  'AekAds Satvan Bellevue Gandhinagar - Digital Display',
  'Digital Display', 'Portrait', '1080x1920', 10,
  'Satvan Bellevue',
  'Satvan Bellevue, Rayasan Road, Gandhinagar, Gujarat 382421',
  'Gandhinagar', 'Gujarat', '382421', 23.16603352, 72.64502773,
  'Residential Society', 730, 'Pedestrian',
  ARRAY['Morning Rush','Evening Leisure'],
  'Indoor', 'Medium',
  '43-inch Dual LED screens at Satvan Bellevue, Rayasan Road. 5 towers, 5 screens serving 180 households.',
  '06:00', '00:00',
  ARRAY['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
  ARRAY['Young Adults (18-25)','Adults (26-40)','Middle Age (41-55)'],
  'Mixed Gender', 'Middle Income',
  ARRAY['Working Professionals','Homemakers','Families'],
  ARRAY['Daily Commuters','Urban Residents'],
  5,
  ARRAY['Daily Living','Commuting'], ARRAY['Relaxed','Routine'],
  true, 5, 275, 30,
  90, 9, 40,
  ARRAY['Video','Static Image'],
  'Digital Display', '43 Inches (1080 x 1920)', '06:00 AM - 12:00 AM',
  'active', true
),
-- 13. Santvihar-1, Koba — 3 screens, 90 households, 350 reach → ₹165/day
(
  'AekAds Santvihar-1 Gandhinagar - Digital Display',
  'Digital Display', 'Portrait', '1080x1920', 10,
  'Santvihar-1',
  'Santvihar-1, Koba, Gandhinagar, Gujarat 382007',
  'Gandhinagar', 'Gujarat', '382007', 23.1529563, 72.64260565,
  'Residential Society', 350, 'Pedestrian',
  ARRAY['Morning Rush','Evening Leisure'],
  'Indoor', 'Medium',
  '43-inch Dual LED screens at Santvihar-1, Koba. 3 towers, 3 screens serving 90 households.',
  '06:00', '00:00',
  ARRAY['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
  ARRAY['Young Adults (18-25)','Adults (26-40)','Middle Age (41-55)'],
  'Mixed Gender', 'Middle Income',
  ARRAY['Working Professionals','Homemakers','Families'],
  ARRAY['Daily Commuters','Urban Residents'],
  5,
  ARRAY['Daily Living','Commuting'], ARRAY['Relaxed','Routine'],
  true, 3, 165, 30,
  90, 9, 40,
  ARRAY['Video','Static Image'],
  'Digital Display', '43 Inches (1080 x 1920)', '06:00 AM - 12:00 AM',
  'active', true
),
-- 14. Samved Green Valley, Sargasan — 9 screens, 320 households, 1100 reach → ₹495/day
(
  'AekAds Samved Green Valley Gandhinagar - Digital Display',
  'Digital Display', 'Portrait', '1080x1920', 10,
  'Samved Green Valley',
  'Samved Green Valley, Sargasan, Gandhinagar, Gujarat 382421',
  'Gandhinagar', 'Gujarat', '382421', 23.19184393, 72.62017878,
  'Residential Society', 1100, 'Pedestrian',
  ARRAY['Morning Rush','Evening Leisure'],
  'Indoor', 'Medium',
  '43-inch Dual LED screens at Samved Green Valley, Sargasan. 9 towers, 9 screens serving 320 households.',
  '06:00', '00:00',
  ARRAY['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
  ARRAY['Young Adults (18-25)','Adults (26-40)','Middle Age (41-55)'],
  'Mixed Gender', 'Middle Income',
  ARRAY['Working Professionals','Homemakers','Families'],
  ARRAY['Daily Commuters','Urban Residents'],
  5,
  ARRAY['Daily Living','Commuting'], ARRAY['Relaxed','Routine'],
  true, 9, 495, 30,
  90, 9, 40,
  ARRAY['Video','Static Image'],
  'Digital Display', '43 Inches (1080 x 1920)', '06:00 AM - 12:00 AM',
  'active', true
),
-- 15. Maruti Amarkunj-2, Sargasan — 6 screens, 156 households, 600 reach → ₹330/day
(
  'AekAds Maruti Amarkunj-2 Gandhinagar - Digital Display',
  'Digital Display', 'Portrait', '1080x1920', 10,
  'Maruti Amarkunj-2',
  'Maruti Amarkunj-2, Sargasan, Gandhinagar, Gujarat 382421',
  'Gandhinagar', 'Gujarat', '382421', 23.19377721, 72.60951888,
  'Residential Society', 600, 'Pedestrian',
  ARRAY['Morning Rush','Evening Leisure'],
  'Indoor', 'Medium',
  '43-inch Dual LED screens at Maruti Amarkunj-2, Sargasan. 6 towers, 6 screens serving 156 households.',
  '06:00', '00:00',
  ARRAY['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
  ARRAY['Young Adults (18-25)','Adults (26-40)','Middle Age (41-55)'],
  'Mixed Gender', 'Middle Income',
  ARRAY['Working Professionals','Homemakers','Families'],
  ARRAY['Daily Commuters','Urban Residents'],
  5,
  ARRAY['Daily Living','Commuting'], ARRAY['Relaxed','Routine'],
  true, 6, 330, 30,
  90, 9, 40,
  ARRAY['Video','Static Image'],
  'Digital Display', '43 Inches (1080 x 1920)', '06:00 AM - 12:00 AM',
  'active', true
),
-- 16. Casario, Randesan — 7 screens, 140 households, 570 reach → ₹385/day
(
  'AekAds Casario Gandhinagar - Digital Display',
  'Digital Display', 'Portrait', '1080x1920', 10,
  'Casario',
  'Casario, Randesan, Gandhinagar, Gujarat 382421',
  'Gandhinagar', 'Gujarat', '382421', 23.17485865, 72.64959513,
  'Residential Society', 570, 'Pedestrian',
  ARRAY['Morning Rush','Evening Leisure'],
  'Indoor', 'Medium',
  '43-inch Dual LED screens at Casario, Randesan. 7 towers, 7 screens serving 140 households.',
  '06:00', '00:00',
  ARRAY['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
  ARRAY['Young Adults (18-25)','Adults (26-40)','Middle Age (41-55)'],
  'Mixed Gender', 'Middle Income',
  ARRAY['Working Professionals','Homemakers','Families'],
  ARRAY['Daily Commuters','Urban Residents'],
  5,
  ARRAY['Daily Living','Commuting'], ARRAY['Relaxed','Routine'],
  true, 7, 385, 30,
  90, 9, 40,
  ARRAY['Video','Static Image'],
  'Digital Display', '43 Inches (1080 x 1920)', '06:00 AM - 12:00 AM',
  'active', true
),
-- 17. Suyansh Harmonica, Kudasan — 2 screens, 74 households, 300 reach → ₹110/day
(
  'AekAds Suyansh Harmonica Gandhinagar - Digital Display',
  'Digital Display', 'Portrait', '1080x1920', 10,
  'Suyansh Harmonica',
  'Suyansh Harmonica, Kudasan, Gandhinagar, Gujarat 382421',
  'Gandhinagar', 'Gujarat', '382421', 23.17813295, 72.631435,
  'Residential Society', 300, 'Pedestrian',
  ARRAY['Morning Rush','Evening Leisure'],
  'Indoor', 'Medium',
  '43-inch Dual LED screens at Suyansh Harmonica, Kudasan. 2 towers, 2 screens serving 74 households.',
  '06:00', '00:00',
  ARRAY['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
  ARRAY['Young Adults (18-25)','Adults (26-40)','Middle Age (41-55)'],
  'Mixed Gender', 'Middle Income',
  ARRAY['Working Professionals','Homemakers','Families'],
  ARRAY['Daily Commuters','Urban Residents'],
  5,
  ARRAY['Daily Living','Commuting'], ARRAY['Relaxed','Routine'],
  true, 2, 110, 30,
  90, 9, 40,
  ARRAY['Video','Static Image'],
  'Digital Display', '43 Inches (1080 x 1920)', '06:00 AM - 12:00 AM',
  'active', true
),
-- 18. Swagat Pelican, Sargasan — 7 screens, 280 households, 1120 reach → ₹385/day
(
  'AekAds Swagat Pelican Gandhinagar - Digital Display',
  'Digital Display', 'Portrait', '1080x1920', 10,
  'Swagat Pelican',
  'Swagat Pelican, Sargasan, Gandhinagar, Gujarat 382421',
  'Gandhinagar', 'Gujarat', '382421', 23.1845856, 72.61298709,
  'Residential Society', 1120, 'Pedestrian',
  ARRAY['Morning Rush','Evening Leisure'],
  'Indoor', 'Medium',
  '43-inch Dual LED screens at Swagat Pelican, Sargasan. 7 towers, 7 screens serving 280 households.',
  '06:00', '00:00',
  ARRAY['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
  ARRAY['Young Adults (18-25)','Adults (26-40)','Middle Age (41-55)'],
  'Mixed Gender', 'Middle Income',
  ARRAY['Working Professionals','Homemakers','Families'],
  ARRAY['Daily Commuters','Urban Residents'],
  5,
  ARRAY['Daily Living','Commuting'], ARRAY['Relaxed','Routine'],
  true, 7, 385, 30,
  90, 9, 40,
  ARRAY['Video','Static Image'],
  'Digital Display', '43 Inches (1080 x 1920)', '06:00 AM - 12:00 AM',
  'active', true
),
-- 19. The Sky Court Shikshapatri, Sargasan — 2 screens, 53 households, 220 reach → ₹110/day
(
  'AekAds Sky Court Shikshapatri Gandhinagar - Digital Display',
  'Digital Display', 'Portrait', '1080x1920', 10,
  'The Sky Court Shikshapatri',
  'The Sky Court Shikshapatri, Sargasan, Gandhinagar, Gujarat 382421',
  'Gandhinagar', 'Gujarat', '382421', 23.19149846, 72.60652849,
  'Residential Society', 220, 'Pedestrian',
  ARRAY['Morning Rush','Evening Leisure'],
  'Indoor', 'Medium',
  '43-inch Dual LED screens at The Sky Court Shikshapatri, Sargasan. 2 towers, 2 screens serving 53 households.',
  '06:00', '00:00',
  ARRAY['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
  ARRAY['Young Adults (18-25)','Adults (26-40)','Middle Age (41-55)'],
  'Mixed Gender', 'Middle Income',
  ARRAY['Working Professionals','Homemakers','Families'],
  ARRAY['Daily Commuters','Urban Residents'],
  5,
  ARRAY['Daily Living','Commuting'], ARRAY['Relaxed','Routine'],
  true, 2, 110, 30,
  90, 9, 40,
  ARRAY['Video','Static Image'],
  'Digital Display', '43 Inches (1080 x 1920)', '06:00 AM - 12:00 AM',
  'active', true
),
-- 20. Santvihar-2, Sargasan — 3 screens (missing households/reach, estimated) → ₹165/day
(
  'AekAds Santvihar-2 Gandhinagar - Digital Display',
  'Digital Display', 'Portrait', '1080x1920', 10,
  'Santvihar-2',
  'Santvihar-2, Sargasan, Gandhinagar, Gujarat 382426',
  'Gandhinagar', 'Gujarat', '382426', 23.15374178, 72.63978776,
  'Residential Society', 300, 'Pedestrian',
  ARRAY['Morning Rush','Evening Leisure'],
  'Indoor', 'Medium',
  '43-inch Dual LED screens at Santvihar-2, Sargasan. 3 towers, 3 screens.',
  '06:00', '00:00',
  ARRAY['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
  ARRAY['Young Adults (18-25)','Adults (26-40)','Middle Age (41-55)'],
  'Mixed Gender', 'Middle Income',
  ARRAY['Working Professionals','Homemakers','Families'],
  ARRAY['Daily Commuters','Urban Residents'],
  5,
  ARRAY['Daily Living','Commuting'], ARRAY['Relaxed','Routine'],
  true, 3, 165, 30,
  90, 9, 40,
  ARRAY['Video','Static Image'],
  'Digital Display', '43 Inches (1080 x 1920)', '06:00 AM - 12:00 AM',
  'active', true
);

-- ============================================================
-- GANDHINAGAR CORPORATE (6 entries, 25 screens)
-- ============================================================

INSERT INTO screens (
  name, category, display_format, resolution, duration_per_slot,
  venue_name, location, city, state, pincode, latitude, longitude,
  venue_category, avg_daily_footfall, traffic_type, time_of_day_activity,
  environment_type, visibility, description,
  custom_operating_hours_start, custom_operating_hours_end,
  custom_operating_days,
  detailed_age_groups, gender_orientation, income_level,
  occupation_mix, lifestyle_tags, avg_dwell_time,
  user_intent, user_mood,
  is_multi_screen, number_of_screens, price_per_day, min_booking_days,
  loop_duration, max_brands_per_loop, playback_slots_per_hour,
  content_types_supported,
  type, size, operational_hours,
  status, owned_by_admin
) VALUES
-- C1. Orbit Mall (Indoor), Kudasan — 13 screens (32"), 350 offices, 10000 reach → ₹1,430/day
(
  'AekAds Orbit Mall Gandhinagar - Digital Display',
  'Digital Display', 'Portrait', '1080x1920', 10,
  'Orbit Mall',
  'Orbit Mall, Kudasan, Gandhinagar, Gujarat 382421',
  'Gandhinagar', 'Gujarat', '382421', 23.18434795, 72.63081108,
  'Mall', 10000, 'Pedestrian',
  ARRAY['Morning Rush','Lunch Hours','Evening Leisure'],
  'Indoor', 'High',
  '32-inch LED screens at Orbit Mall, Kudasan. 13 screens across the mall. 10000 daily footfall.',
  '06:00', '00:00',
  ARRAY['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
  ARRAY['Young Adults (18-25)','Adults (26-40)','Middle Age (41-55)'],
  'Mixed Gender', 'Upper Middle Income',
  ARRAY['Working Professionals','Shoppers','Families'],
  ARRAY['Shopping','Entertainment'],
  30,
  ARRAY['Shopping','Entertainment'], ARRAY['Relaxed','Social'],
  true, 13, 1430, 30,
  90, 9, 40,
  ARRAY['Video','Static Image'],
  'Digital Display', '32 Inches (1080 x 1920)', '06:00 AM - 12:00 AM',
  'active', true
),
-- C2. Orbit Mall (Outdoor LED), Kudasan — 1 screen (22x13 ft), 10000 reach → ₹3,667/day
(
  'AekAds Orbit Mall Gandhinagar - Outdoor LED',
  'LED Display', 'Landscape', '1920x1080', 15,
  'Orbit Mall',
  'Orbit Mall, Kudasan, Gandhinagar, Gujarat 382421',
  'Gandhinagar', 'Gujarat', '382421', 23.18434795, 72.63081108,
  'Outdoor', 10000, 'Vehicular',
  ARRAY['Morning Rush','Lunch Hours','Evening Leisure','Late Night'],
  'Outdoor Digital', 'High',
  '22x13 ft outdoor LED display at Orbit Mall, Kudasan. High-visibility location.',
  '06:00', '00:00',
  ARRAY['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
  ARRAY['Young Adults (18-25)','Adults (26-40)','Middle Age (41-55)'],
  'Mixed Gender', 'Upper Middle Income',
  ARRAY['Commuters','Shoppers','Local Residents'],
  ARRAY['Shopping','Entertainment'],
  5,
  ARRAY['Shopping','Commuting'], ARRAY['Relaxed','Leisure'],
  false, 1, 3667, 30,
  90, 6, 40,
  ARRAY['Video','Static Image'],
  'LED Display', '22x13 ft', '06:00 AM - 12:00 AM',
  'active', true
),
-- C3. The Urbania, Kudasan — 4 screens (43"), 272 offices, 3000 reach → ₹440/day
(
  'AekAds The Urbania Gandhinagar - Digital Display',
  'Digital Display', 'Portrait', '1080x1920', 10,
  'The Urbania',
  'The Urbania, Kudasan, Gandhinagar, Gujarat 382421',
  'Gandhinagar', 'Gujarat', '382421', 23.17896111, 72.62860975,
  'Corporate Office', 3000, 'Pedestrian',
  ARRAY['Morning Rush','Lunch Hours','Evening Leisure'],
  'Indoor', 'High',
  '43-inch Dual LED screens at The Urbania, Kudasan. 4 screens across 272 offices.',
  '06:00', '00:00',
  ARRAY['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
  ARRAY['Young Adults (18-25)','Adults (26-40)','Middle Age (41-55)'],
  'Mixed Gender', 'Upper Middle Income',
  ARRAY['Working Professionals','Business Owners'],
  ARRAY['Corporate','Business District'],
  10,
  ARRAY['Business','Work'], ARRAY['Focused','Professional'],
  true, 4, 440, 30,
  90, 9, 40,
  ARRAY['Video','Static Image'],
  'Digital Display', '43 Inches (1080 x 1920)', '06:00 AM - 12:00 AM',
  'active', true
),
-- C4. Pramukh Square, Sargasan — 1 screen (43"), 110 offices, 1200 reach → ₹110/day
(
  'AekAds Pramukh Square Gandhinagar - Digital Display',
  'Digital Display', 'Portrait', '1080x1920', 10,
  'Pramukh Square',
  'Pramukh Square, Sargasan, Gandhinagar, Gujarat 382421',
  'Gandhinagar', 'Gujarat', '382421', 23.18566932, 72.6193009,
  'Corporate Office', 1200, 'Pedestrian',
  ARRAY['Morning Rush','Lunch Hours','Evening Leisure'],
  'Indoor', 'High',
  '43-inch Dual LED screen at Pramukh Square, Sargasan. 1 screen across 110 offices.',
  '06:00', '00:00',
  ARRAY['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
  ARRAY['Young Adults (18-25)','Adults (26-40)','Middle Age (41-55)'],
  'Mixed Gender', 'Upper Middle Income',
  ARRAY['Working Professionals','Business Owners'],
  ARRAY['Corporate','Business District'],
  10,
  ARRAY['Business','Work'], ARRAY['Focused','Professional'],
  false, 1, 110, 30,
  90, 9, 40,
  ARRAY['Video','Static Image'],
  'Digital Display', '43 Inches (1080 x 1920)', '06:00 AM - 12:00 AM',
  'active', true
),
-- C5. Vrundavan Trade Center (VTC), Sargasan — 5 screens (43"), 316 offices, 3000 reach → ₹550/day
(
  'AekAds Vrundavan Trade Center Gandhinagar - Digital Display',
  'Digital Display', 'Portrait', '1080x1920', 10,
  'Vrundavan Trade Center',
  'Vrundavan Trade Center (VTC), Sargasan, Gandhinagar, Gujarat 382421',
  'Gandhinagar', 'Gujarat', '382421', 23.18293999, 72.62884044,
  'Corporate Office', 3000, 'Pedestrian',
  ARRAY['Morning Rush','Lunch Hours','Evening Leisure'],
  'Indoor', 'High',
  '43-inch Dual LED screens at Vrundavan Trade Center, Sargasan. 5 screens across 316 offices.',
  '06:00', '00:00',
  ARRAY['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
  ARRAY['Young Adults (18-25)','Adults (26-40)','Middle Age (41-55)'],
  'Mixed Gender', 'Upper Middle Income',
  ARRAY['Working Professionals','Business Owners'],
  ARRAY['Corporate','Business District'],
  10,
  ARRAY['Business','Work'], ARRAY['Focused','Professional'],
  true, 5, 550, 30,
  90, 9, 40,
  ARRAY['Video','Static Image'],
  'Digital Display', '43 Inches (1080 x 1920)', '06:00 AM - 12:00 AM',
  'active', true
),
-- C6. Pramukh Aayan, Sargasan — 1 screen (43"), 90 offices, 1000 reach → ₹110/day
(
  'AekAds Pramukh Aayan Gandhinagar - Digital Display',
  'Digital Display', 'Portrait', '1080x1920', 10,
  'Pramukh Aayan',
  'Pramukh Aayan, Sargasan, Gandhinagar, Gujarat 382421',
  'Gandhinagar', 'Gujarat', '382421', 23.18648375, 72.61991598,
  'Corporate Office', 1000, 'Pedestrian',
  ARRAY['Morning Rush','Lunch Hours','Evening Leisure'],
  'Indoor', 'High',
  '43-inch Dual LED screen at Pramukh Aayan, Sargasan. 1 screen across 90 offices.',
  '06:00', '00:00',
  ARRAY['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
  ARRAY['Young Adults (18-25)','Adults (26-40)','Middle Age (41-55)'],
  'Mixed Gender', 'Upper Middle Income',
  ARRAY['Working Professionals','Business Owners'],
  ARRAY['Corporate','Business District'],
  10,
  ARRAY['Business','Work'], ARRAY['Focused','Professional'],
  false, 1, 110, 30,
  90, 9, 40,
  ARRAY['Video','Static Image'],
  'Digital Display', '43 Inches (1080 x 1920)', '06:00 AM - 12:00 AM',
  'active', true
);

COMMIT;
