-- ============================================================
-- INSERT: AekAds Reliance Smart Bazaar Ahmedabad (12 stores, 145 screens)
-- Network: AekAds | City: Ahmedabad | State: Gujarat
-- Rate: ₹40,000/store/month net
-- price_per_day = round(40000 / 30 × 1.1) = ₹1,467 per store
-- Duration: 10 sec per slot | Loop: 90 sec (1.5 min)
-- min_booking_days = 30 (monthly commitment)
-- NOTE: Coordinates are approximate for store locations
-- ============================================================

BEGIN;

INSERT INTO screens (
  name, category, display_format, resolution, duration_per_slot,
  venue_name, location, city, state, pincode, latitude, longitude,
  venue_category, avg_daily_footfall, traffic_type, time_of_day_activity,
  environment_type, visibility, description,
  custom_operating_hours_start, custom_operating_hours_end,
  custom_operating_days,
  detailed_age_groups, gender_orientation, income_level,
  occupation_mix, lifestyle_tags, avg_dwell_time,
  user_intent, user_mood,
  is_multi_screen, number_of_screens, price_per_day, min_booking_days,
  loop_duration, max_brands_per_loop, playback_slots_per_hour,
  content_types_supported,
  type, size, operational_hours,
  status, owned_by_admin
) VALUES
-- 1. ISKCON — 15 screens
(
  'AekAds Reliance Smart Bazaar ISKCON Ahmedabad - Digital Display',
  'Digital Display', 'Portrait', '1080x1920', 10,
  'Reliance Smart Bazaar ISKCON',
  'ISKCON, SG Highway, Ahmedabad, Gujarat 380015',
  'Ahmedabad', 'Gujarat', '380015', 23.0275, 72.5072,
  'Retail Store', 3000, 'Pedestrian',
  ARRAY['Morning Rush','Lunch Hours','Evening Leisure'],
  'Indoor', 'High',
  'Digital display network at Reliance Smart Bazaar ISKCON, Ahmedabad. 15 screens engaging daily shoppers.',
  '06:00', '00:00',
  ARRAY['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
  ARRAY['Young Adults (18-25)','Adults (26-40)','Middle Age (41-55)'],
  'Mixed Gender', 'Middle Income',
  ARRAY['Homemakers','Working Professionals','Families'],
  ARRAY['Daily Shoppers','Value Seekers'],
  30,
  ARRAY['Shopping','Daily Essentials'], ARRAY['Purposeful','Routine'],
  true, 15, 1467, 30,
  90, 9, 40,
  ARRAY['Video','Static Image'],
  'Digital Display', '32/43 Inches (1080 x 1920)', '06:00 AM - 12:00 AM',
  'active', true
),
-- 2. HighStreet Navarangpura — 10 screens
(
  'AekAds Reliance Smart Bazaar HighStreet Ahmedabad - Digital Display',
  'Digital Display', 'Portrait', '1080x1920', 10,
  'Reliance Smart Bazaar HighStreet',
  'HighStreet, Navarangpura, Ahmedabad, Gujarat 380009',
  'Ahmedabad', 'Gujarat', '380009', 23.0390, 72.5560,
  'Retail Store', 3000, 'Pedestrian',
  ARRAY['Morning Rush','Lunch Hours','Evening Leisure'],
  'Indoor', 'High',
  'Digital display network at Reliance Smart Bazaar HighStreet, Navarangpura. 10 screens.',
  '06:00', '00:00',
  ARRAY['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
  ARRAY['Young Adults (18-25)','Adults (26-40)','Middle Age (41-55)'],
  'Mixed Gender', 'Middle Income',
  ARRAY['Homemakers','Working Professionals','Families'],
  ARRAY['Daily Shoppers','Value Seekers'],
  30,
  ARRAY['Shopping','Daily Essentials'], ARRAY['Purposeful','Routine'],
  true, 10, 1467, 30,
  90, 9, 40,
  ARRAY['Video','Static Image'],
  'Digital Display', '32/43 Inches (1080 x 1920)', '06:00 AM - 12:00 AM',
  'active', true
),
-- 3. Drive In Gurukul — 14 screens
(
  'AekAds Reliance Smart Bazaar Drive In Ahmedabad - Digital Display',
  'Digital Display', 'Portrait', '1080x1920', 10,
  'Reliance Smart Bazaar Drive In',
  'Drive In, Gurukul, Ahmedabad, Gujarat 380052',
  'Ahmedabad', 'Gujarat', '380052', 23.0440, 72.5412,
  'Retail Store', 3000, 'Pedestrian',
  ARRAY['Morning Rush','Lunch Hours','Evening Leisure'],
  'Indoor', 'High',
  'Digital display network at Reliance Smart Bazaar Drive In, Gurukul. 14 screens.',
  '06:00', '00:00',
  ARRAY['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
  ARRAY['Young Adults (18-25)','Adults (26-40)','Middle Age (41-55)'],
  'Mixed Gender', 'Middle Income',
  ARRAY['Homemakers','Working Professionals','Families'],
  ARRAY['Daily Shoppers','Value Seekers'],
  30,
  ARRAY['Shopping','Daily Essentials'], ARRAY['Purposeful','Routine'],
  true, 14, 1467, 30,
  90, 9, 40,
  ARRAY['Video','Static Image'],
  'Digital Display', '32/43 Inches (1080 x 1920)', '06:00 AM - 12:00 AM',
  'active', true
),
-- 4. Smart Yash Pinnacle Ashram Road — 10 screens
(
  'AekAds Reliance Smart Bazaar Yash Pinnacle Ahmedabad - Digital Display',
  'Digital Display', 'Portrait', '1080x1920', 10,
  'Reliance Smart Bazaar Yash Pinnacle',
  'Yash Pinnacle, Ashram Road, Ahmedabad, Gujarat 380009',
  'Ahmedabad', 'Gujarat', '380009', 23.0280, 72.5680,
  'Retail Store', 3000, 'Pedestrian',
  ARRAY['Morning Rush','Lunch Hours','Evening Leisure'],
  'Indoor', 'High',
  'Digital display network at Reliance Smart Bazaar Yash Pinnacle, Ashram Road. 10 screens.',
  '06:00', '00:00',
  ARRAY['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
  ARRAY['Young Adults (18-25)','Adults (26-40)','Middle Age (41-55)'],
  'Mixed Gender', 'Middle Income',
  ARRAY['Homemakers','Working Professionals','Families'],
  ARRAY['Daily Shoppers','Value Seekers'],
  30,
  ARRAY['Shopping','Daily Essentials'], ARRAY['Purposeful','Routine'],
  true, 10, 1467, 30,
  90, 9, 40,
  ARRAY['Video','Static Image'],
  'Digital Display', '32/43 Inches (1080 x 1920)', '06:00 AM - 12:00 AM',
  'active', true
),
-- 5. Yash Arrian Gurukul — 10 screens
(
  'AekAds Reliance Smart Bazaar Yash Arrian Ahmedabad - Digital Display',
  'Digital Display', 'Portrait', '1080x1920', 10,
  'Reliance Smart Bazaar Yash Arrian',
  'Yash Arrian, Gurukul, Ahmedabad, Gujarat 380052',
  'Ahmedabad', 'Gujarat', '380052', 23.0430, 72.5430,
  'Retail Store', 3000, 'Pedestrian',
  ARRAY['Morning Rush','Lunch Hours','Evening Leisure'],
  'Indoor', 'High',
  'Digital display network at Reliance Smart Bazaar Yash Arrian, Gurukul. 10 screens.',
  '06:00', '00:00',
  ARRAY['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
  ARRAY['Young Adults (18-25)','Adults (26-40)','Middle Age (41-55)'],
  'Mixed Gender', 'Middle Income',
  ARRAY['Homemakers','Working Professionals','Families'],
  ARRAY['Daily Shoppers','Value Seekers'],
  30,
  ARRAY['Shopping','Daily Essentials'], ARRAY['Purposeful','Routine'],
  true, 10, 1467, 30,
  90, 9, 40,
  ARRAY['Video','Static Image'],
  'Digital Display', '32/43 Inches (1080 x 1920)', '06:00 AM - 12:00 AM',
  'active', true
),
-- 6. Advance Mills Shahibaug — 10 screens
(
  'AekAds Reliance Smart Bazaar Advance Mills Ahmedabad - Digital Display',
  'Digital Display', 'Portrait', '1080x1920', 10,
  'Reliance Smart Bazaar Advance Mills',
  'Advance Mills, Shahibaug, Ahmedabad, Gujarat 380004',
  'Ahmedabad', 'Gujarat', '380004', 23.0540, 72.5830,
  'Retail Store', 3000, 'Pedestrian',
  ARRAY['Morning Rush','Lunch Hours','Evening Leisure'],
  'Indoor', 'High',
  'Digital display network at Reliance Smart Bazaar Advance Mills, Shahibaug. 10 screens.',
  '06:00', '00:00',
  ARRAY['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
  ARRAY['Young Adults (18-25)','Adults (26-40)','Middle Age (41-55)'],
  'Mixed Gender', 'Middle Income',
  ARRAY['Homemakers','Working Professionals','Families'],
  ARRAY['Daily Shoppers','Value Seekers'],
  30,
  ARRAY['Shopping','Daily Essentials'], ARRAY['Purposeful','Routine'],
  true, 10, 1467, 30,
  90, 9, 40,
  ARRAY['Video','Static Image'],
  'Digital Display', '32/43 Inches (1080 x 1920)', '06:00 AM - 12:00 AM',
  'active', true
),
-- 7. C3 Celebration Mall South Bopal — 16 screens
(
  'AekAds Reliance Smart Bazaar C3 Celebration Ahmedabad - Digital Display',
  'Digital Display', 'Portrait', '1080x1920', 10,
  'Reliance Smart Bazaar C3 Celebration Mall',
  'C3 Celebration Mall, South Bopal, Ahmedabad, Gujarat 380058',
  'Ahmedabad', 'Gujarat', '380058', 23.0249, 72.4684,
  'Retail Store', 4000, 'Pedestrian',
  ARRAY['Morning Rush','Lunch Hours','Evening Leisure'],
  'Indoor', 'High',
  'Digital display network at Reliance Smart Bazaar C3 Celebration Mall, South Bopal. 16 screens.',
  '06:00', '00:00',
  ARRAY['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
  ARRAY['Young Adults (18-25)','Adults (26-40)','Middle Age (41-55)'],
  'Mixed Gender', 'Middle Income',
  ARRAY['Homemakers','Working Professionals','Families'],
  ARRAY['Daily Shoppers','Value Seekers'],
  30,
  ARRAY['Shopping','Daily Essentials'], ARRAY['Purposeful','Routine'],
  true, 16, 1467, 30,
  90, 9, 40,
  ARRAY['Video','Static Image'],
  'Digital Display', '32/43 Inches (1080 x 1920)', '06:00 AM - 12:00 AM',
  'active', true
),
-- 8. ALPHA ONE Vastrapur — 10 screens
(
  'AekAds Reliance Smart Bazaar Alpha One Ahmedabad - Digital Display',
  'Digital Display', 'Portrait', '1080x1920', 10,
  'Reliance Smart Bazaar Alpha One',
  'Alpha One Mall, Vastrapur, Ahmedabad, Gujarat 380015',
  'Ahmedabad', 'Gujarat', '380015', 23.0356, 72.5289,
  'Retail Store', 4000, 'Pedestrian',
  ARRAY['Morning Rush','Lunch Hours','Evening Leisure'],
  'Indoor', 'High',
  'Digital display network at Reliance Smart Bazaar Alpha One Mall, Vastrapur. 10 screens.',
  '06:00', '00:00',
  ARRAY['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
  ARRAY['Young Adults (18-25)','Adults (26-40)','Middle Age (41-55)'],
  'Mixed Gender', 'Middle Income',
  ARRAY['Homemakers','Working Professionals','Families'],
  ARRAY['Daily Shoppers','Value Seekers'],
  30,
  ARRAY['Shopping','Daily Essentials'], ARRAY['Purposeful','Routine'],
  true, 10, 1467, 30,
  90, 9, 40,
  ARRAY['Video','Static Image'],
  'Digital Display', '32/43 Inches (1080 x 1920)', '06:00 AM - 12:00 AM',
  'active', true
),
-- 9. ChandKheda — 12 screens
(
  'AekAds Reliance Smart Bazaar Chandkheda Ahmedabad - Digital Display',
  'Digital Display', 'Portrait', '1080x1920', 10,
  'Reliance Smart Bazaar Chandkheda',
  'Chandkheda, Ahmedabad, Gujarat 382424',
  'Ahmedabad', 'Gujarat', '382424', 23.1130, 72.5870,
  'Retail Store', 3000, 'Pedestrian',
  ARRAY['Morning Rush','Lunch Hours','Evening Leisure'],
  'Indoor', 'High',
  'Digital display network at Reliance Smart Bazaar Chandkheda. 12 screens.',
  '06:00', '00:00',
  ARRAY['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
  ARRAY['Young Adults (18-25)','Adults (26-40)','Middle Age (41-55)'],
  'Mixed Gender', 'Middle Income',
  ARRAY['Homemakers','Working Professionals','Families'],
  ARRAY['Daily Shoppers','Value Seekers'],
  30,
  ARRAY['Shopping','Daily Essentials'], ARRAY['Purposeful','Routine'],
  true, 12, 1467, 30,
  90, 9, 40,
  ARRAY['Video','Static Image'],
  'Digital Display', '32/43 Inches (1080 x 1920)', '06:00 AM - 12:00 AM',
  'active', true
),
-- 10. Sola Science City — 12 screens
(
  'AekAds Reliance Smart Bazaar Sola Ahmedabad - Digital Display',
  'Digital Display', 'Portrait', '1080x1920', 10,
  'Reliance Smart Bazaar Sola Science City',
  'Sola, Science City Road, Ahmedabad, Gujarat 380060',
  'Ahmedabad', 'Gujarat', '380060', 23.0780, 72.5200,
  'Retail Store', 3000, 'Pedestrian',
  ARRAY['Morning Rush','Lunch Hours','Evening Leisure'],
  'Indoor', 'High',
  'Digital display network at Reliance Smart Bazaar Sola Science City. 12 screens.',
  '06:00', '00:00',
  ARRAY['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
  ARRAY['Young Adults (18-25)','Adults (26-40)','Middle Age (41-55)'],
  'Mixed Gender', 'Middle Income',
  ARRAY['Homemakers','Working Professionals','Families'],
  ARRAY['Daily Shoppers','Value Seekers'],
  30,
  ARRAY['Shopping','Daily Essentials'], ARRAY['Purposeful','Routine'],
  true, 12, 1467, 30,
  90, 9, 40,
  ARRAY['Video','Static Image'],
  'Digital Display', '32/43 Inches (1080 x 1920)', '06:00 AM - 12:00 AM',
  'active', true
),
-- 11. Stratum Nehrunagar — 11 screens
(
  'AekAds Reliance Smart Bazaar Stratum Ahmedabad - Digital Display',
  'Digital Display', 'Portrait', '1080x1920', 10,
  'Reliance Smart Bazaar Stratum',
  'Stratum, Nehrunagar, Ahmedabad, Gujarat 380015',
  'Ahmedabad', 'Gujarat', '380015', 23.0412, 72.5504,
  'Retail Store', 3000, 'Pedestrian',
  ARRAY['Morning Rush','Lunch Hours','Evening Leisure'],
  'Indoor', 'High',
  'Digital display network at Reliance Smart Bazaar Stratum, Nehrunagar. 11 screens.',
  '06:00', '00:00',
  ARRAY['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
  ARRAY['Young Adults (18-25)','Adults (26-40)','Middle Age (41-55)'],
  'Mixed Gender', 'Middle Income',
  ARRAY['Homemakers','Working Professionals','Families'],
  ARRAY['Daily Shoppers','Value Seekers'],
  30,
  ARRAY['Shopping','Daily Essentials'], ARRAY['Purposeful','Routine'],
  true, 11, 1467, 30,
  90, 9, 40,
  ARRAY['Video','Static Image'],
  'Digital Display', '32/43 Inches (1080 x 1920)', '06:00 AM - 12:00 AM',
  'active', true
),
-- 12. Zundal — 15 screens
(
  'AekAds Reliance Smart Bazaar Zundal Ahmedabad - Digital Display',
  'Digital Display', 'Portrait', '1080x1920', 10,
  'Reliance Smart Bazaar Zundal',
  'Zundal, Ahmedabad, Gujarat 382421',
  'Ahmedabad', 'Gujarat', '382421', 23.1320, 72.5710,
  'Retail Store', 3000, 'Pedestrian',
  ARRAY['Morning Rush','Lunch Hours','Evening Leisure'],
  'Indoor', 'High',
  'Digital display network at Reliance Smart Bazaar Zundal. 15 screens.',
  '06:00', '00:00',
  ARRAY['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
  ARRAY['Young Adults (18-25)','Adults (26-40)','Middle Age (41-55)'],
  'Mixed Gender', 'Middle Income',
  ARRAY['Homemakers','Working Professionals','Families'],
  ARRAY['Daily Shoppers','Value Seekers'],
  30,
  ARRAY['Shopping','Daily Essentials'], ARRAY['Purposeful','Routine'],
  true, 15, 1467, 30,
  90, 9, 40,
  ARRAY['Video','Static Image'],
  'Digital Display', '32/43 Inches (1080 x 1920)', '06:00 AM - 12:00 AM',
  'active', true
);

COMMIT;
